---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  replicas: {{ .Values.container.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: {{ .Values.container.port }}
