---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
