---
container:
  replicas: 4

ingress:
  lbGroup: YOUR_ALB_NAME
  host: YOUR_DOMAINNAME
  #see in aws console -> securitiy groups -> Security group name > clsutername-alb (acaternberg-tf-02-alb)  an grep the securitygroup-id
  securityGroup: sg-123456789 # PUT YOURS
